exclude: [vendor]
markdown: redcarpet
highlighter: pygments

gems:
  - jemoji
  - jekyll-paginate

url: "http://luisvasconcellos.com"

name: 'Luis Vasconcellos'
email: luis@luisvasconcellos.com

author: 'Luis Vasconcellos'
author_image: "/assets/images/luis.jpg"
author_job_title: Full Stack Developer

paginate:	5
paginate_path: "blog/page:num"
