me:
  name: Luis Vasconcellos
  phone: '+55 21 995100576'
  email: luis@luisvasconcellos.com
  location: São Paulo, Brazil
  website: http://luisvasconcellos.com

  occupation: Software Engineer

  social:
    medium: https://medium.com/@lfv89
    instagram: https://instagram.com/lfv89
    twitter: http://twitter.com/lfv89
    github: http://github.com/lfv89
    linkedin: https://br.linkedin.com/in/lfv89

employer:
  name: enjoei.com
  url: https://enjoei.com.br

collections:
  pages:
    output: true
